import os
import sys


CURRENT_DIR = os.path.dirname(os.path.realpath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

from msn_nodes import (
    NODE_CLASS_MAPPINGS as GATEWAY_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GATEWAY_DISPLAY_MAPPINGS,
)
from content_filter import (
    NODE_CLASS_MAPPINGS as FILTER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FILTER_DISPLAY_MAPPINGS,
)
from media_loader import (
    NODE_CLASS_MAPPINGS as MEDIA_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MEDIA_DISPLAY_MAPPINGS,
)
from thumbnail_save import (
    NODE_CLASS_MAPPINGS as THUMB_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as THUMB_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(GATEWAY_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILTER_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MEDIA_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(THUMB_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(GATEWAY_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(FILTER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MEDIA_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(THUMB_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
